import { onAuthStateChanged } from "firebase/auth";
import { collection, getDocs, query, where } from "firebase/firestore";
import { auth, db } from "./firebase";

const API = "https://mindmate-kuqp.onrender.com";
const moodMap = {
  great: { emoji: "😄", label: "Great" },
  good: { emoji: "😌", label: "Good" },
  okay: { emoji: "😐", label: "Okay" },
  low: { emoji: "😔", label: "Low" },
  rough: { emoji: "😣", label: "Rough" },
};

const style = document.createElement("style");
style.textContent = `
.mm-phase-btn{width:100%;margin:8px 0 0;padding:14px 17px;border:0;border-radius:14px;background:#e6dcff;color:#443477;text-align:left;font-size:15px;font-weight:700;cursor:pointer}
.mm-phase-btn:hover{background:#d9c9ff}
.mm-phase-overlay{position:fixed;inset:0;z-index:10020;background:rgba(30,20,50,.62);display:grid;place-items:center;padding:20px}
.mm-phase-modal{width:min(900px,96vw);max-height:88vh;overflow:auto;background:#fffafc;border:1px solid #ddd0f5;border-radius:24px;box-shadow:0 25px 70px rgba(25,15,55,.35);padding:24px;color:#403267;font-family:Arial,sans-serif}
.mm-phase-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px}.mm-phase-head h2{margin:0 0 5px}.mm-phase-head p{margin:0;color:#887b9d;font-size:13px}.mm-phase-close{border:0;background:transparent;font-size:25px;color:#756986;cursor:pointer}
.mm-phase-tabs{display:flex;gap:8px;margin:20px 0 16px;flex-wrap:wrap}.mm-phase-tab{border:1px solid #ddd2f1;border-radius:12px;padding:9px 14px;background:#fff;color:#5c4787;font-weight:700;cursor:pointer}.mm-phase-tab.active{background:#7655d3;color:#fff;border-color:#7655d3}
.mm-phase-card{border:1px solid #e0d6f0;border-radius:18px;background:#fff;padding:18px}.mm-phase-input{width:100%;box-sizing:border-box;border:1px solid #d9cfee;border-radius:13px;padding:13px;outline:0;resize:vertical;min-height:52px;color:#443967}.mm-phase-input:focus{border-color:#9275d5;box-shadow:0 0 0 3px #eee7ff}.mm-phase-primary{margin-top:10px;border:0;border-radius:12px;padding:11px 16px;background:#7655d3;color:#fff;font-weight:700;cursor:pointer}.mm-phase-answer{margin-top:15px;padding:15px;border-radius:14px;background:#f4efff;line-height:1.6;color:#55476f;white-space:pre-wrap}.mm-phase-suggest{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.mm-phase-suggest button{border:1px solid #ddd2f1;background:#faf8ff;color:#624d8c;border-radius:999px;padding:7px 10px;cursor:pointer;font-size:12px}
.mm-calendar-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.mm-calendar-head button{border:0;background:#eee7ff;border-radius:9px;padding:7px 11px;color:#594582;font-weight:700;cursor:pointer}.mm-calendar-title{font-weight:700;font-size:17px}.mm-calendar{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}.mm-cal-name{text-align:center;font-size:11px;color:#9589a7;padding:4px}.mm-day{min-height:65px;border:1px solid #e5ddf0;border-radius:10px;padding:6px;background:#fff;position:relative}.mm-day.empty{background:#faf8fc}.mm-day-num{font-size:11px;color:#887b9d}.mm-day-mood{display:block;text-align:center;font-size:24px;margin-top:5px}.mm-day.today{border-color:#8c6bda;box-shadow:inset 0 0 0 1px #8c6bda}.mm-day-entry{font-size:9px;color:#8b7d9d;text-align:center}
.mm-growth-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:16px}.mm-growth-stat{padding:15px;border-radius:15px;background:#f5f0ff}.mm-growth-stat strong{display:block;font-size:22px;color:#5a4194}.mm-growth-stat span{font-size:11px;color:#887b9d}.mm-growth-timeline{display:flex;gap:10px;align-items:flex-end;height:220px;padding:15px 10px 5px;border-bottom:1px solid #ddd4eb}.mm-growth-bar-wrap{flex:1;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;height:100%;gap:5px}.mm-growth-bar{width:min(45px,70%);min-height:5px;border-radius:9px 9px 2px 2px;background:linear-gradient(to top,#7655d3,#bba2ef)}.mm-growth-label{font-size:10px;color:#887b9d}.mm-growth-mood{font-size:17px}.mm-growth-note{margin-top:14px;padding:13px;border-radius:13px;background:#fff5e8;color:#735c43;font-size:13px;line-height:1.5}
.dark-mode .mm-phase-modal{background:#241f32;color:#eee7ff}.dark-mode .mm-phase-card,.dark-mode .mm-day{background:#2d273c;border-color:#4b4262}.dark-mode .mm-phase-input{background:#302a40;color:#eee7ff;border-color:#514668}.dark-mode .mm-phase-answer{background:#38304b;color:#e9e0ff}.dark-mode .mm-phase-tab{background:#302a40;color:#ddd1f4;border-color:#514668}.dark-mode .mm-phase-tab.active{background:#7655d3;color:#fff}.dark-mode .mm-calendar-title,.dark-mode .mm-day-num{color:#eee7ff}.dark-mode .mm-growth-stat{background:#38304b}.dark-mode .mm-growth-note{background:#40352b;color:#f1dfc8}
@media(max-width:650px){.mm-phase-modal{padding:17px}.mm-growth-grid{grid-template-columns:1fr}.mm-day{min-height:55px}}
`;
document.head.appendChild(style);

let user = null;
let entries = [];
let modal = null;
let activeTab = "ask";
let calendarDate = new Date();

function dateOf(item){return item?.createdAt?.toDate ? item.createdAt.toDate() : new Date(item?.createdAt || 0)}
function dateKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function formatDate(d){return d.toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}
async function loadEntries(){if(!user){entries=[];return}try{const q=query(collection(db,"journalEntries"),where("userId","==",user.uid));const snap=await getDocs(q);entries=snap.docs.map(x=>({id:x.id,...x.data()})).sort((a,b)=>dateOf(b)-dateOf(a))}catch(e){console.error("Phase 1 entries error",e);entries=[]}}
function close(){modal?.remove();modal=null}
function ensureButton(){if(!user){document.querySelector(".mm-phase-btn")?.remove();return}const side=document.querySelector(".sidebar");if(!side||document.querySelector(".mm-phase-btn"))return;const b=document.createElement("button");b.className="mm-phase-btn";b.innerHTML="🧠 MindMate Insights";b.onclick=()=>open();const bottom=side.querySelector(".sidebar-bottom");side.insertBefore(b,bottom||null)}
function open(tab="ask"){activeTab=tab;close();modal=document.createElement("div");modal.className="mm-phase-overlay";modal.innerHTML=`<div class="mm-phase-modal"><div class="mm-phase-head"><div><h2>🧠 MindMate Insights</h2><p>Your journal, your patterns, your private space.</p></div><button class="mm-phase-close">×</button></div><div class="mm-phase-tabs"><button class="mm-phase-tab" data-tab="ask">🧠 Ask MindMate</button><button class="mm-phase-tab" data-tab="calendar">📊 Mood Calendar</button><button class="mm-phase-tab" data-tab="growth">🌱 Your Growth</button></div><div class="mm-phase-content"></div></div>`;document.body.appendChild(modal);modal.querySelector(".mm-phase-close").onclick=close;modal.addEventListener("click",e=>{if(e.target===modal)close()});modal.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;render()});render()}
function render(){if(!modal)return;modal.querySelectorAll(".mm-phase-tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===activeTab));const c=modal.querySelector(".mm-phase-content");if(activeTab==="ask")ask(c);if(activeTab==="calendar")calendar(c);if(activeTab==="growth")growth(c)}
function ask(c){c.innerHTML=`<div class="mm-phase-card"><h3 style="margin-top:0">Ask anything about your journal 💜</h3><p style="color:#887b9d;font-size:13px">MindMate can look across your saved entries and help you spot themes, memories, and patterns.</p><div class="mm-phase-suggest"><button>What has been on my mind lately?</button><button>What makes me happiest?</button><button>What patterns do you notice?</button><button>What should I focus on?</button></div><textarea class="mm-phase-input" id="mm-question" placeholder="Ask MindMate something..."></textarea><button class="mm-phase-primary" id="mm-ask">✨ Ask MindMate</button><div id="mm-answer"></div></div>`;const q=modal.querySelector("#mm-question");modal.querySelectorAll(".mm-phase-suggest button").forEach(b=>b.onclick=()=>{q.value=b.textContent;q.focus()});modal.querySelector("#mm-ask").onclick=async()=>{const question=q.value.trim(),answer=modal.querySelector("#mm-answer");if(!question){q.focus();return}answer.innerHTML='<div class="mm-phase-answer">Thinking about your journal... ✨</div>';try{const payload=entries.map(x=>({text:x.text||"",mood:x.mood||null,date:formatDate(dateOf(x))}));const r=await fetch(`${API}/ask`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question,entries:payload})});const d=await r.json();if(!r.ok)throw new Error(d.error||"Request failed");answer.innerHTML=`<div class="mm-phase-answer">${escapeHtml(d.answer)}</div>`}catch(e){console.error(e);answer.innerHTML='<div class="mm-phase-answer">I could not reach MindMate right now. Please try again in a moment.</div>'}}}
function escapeHtml(s){const d=document.createElement("div");d.textContent=s||"";return d.innerHTML}
function calendar(c){const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),start=first.getDay();const map={};entries.forEach(x=>{const d=dateOf(x),k=dateKey(d);if(!map[k])map[k]=[];map[k].push(x)});let h=`<div class="mm-phase-card"><div class="mm-calendar-head"><button id="mm-prev">‹</button><div class="mm-calendar-title">${calendarDate.toLocaleString("en-IN",{month:"long",year:"numeric"})}</div><button id="mm-next">›</button></div><div class="mm-calendar">${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>`<div class="mm-cal-name">${x}</div>`).join("")}`;for(let i=0;i<start;i++)h+='<div class="mm-day empty"></div>';for(let day=1;day<=days;day++){const d=new Date(y,m,day),list=map[dateKey(d)]||[],mood=list.find(x=>x.mood)?.mood;const today=dateKey(d)===dateKey(new Date());h+=`<div class="mm-day ${today?'today':''}"><span class="mm-day-num">${day}</span>${mood?`<span class="mm-day-mood">${moodMap[mood]?.emoji||'💜'}</span>`:''}${list.length?`<div class="mm-day-entry">${list.length} ${list.length===1?'entry':'entries'}</div>`:''}</div>`}h+='</div><p style="margin:13px 0 0;color:#887b9d;font-size:12px">Your saved mood check-ins appear on the days you recorded them.</p></div>';c.innerHTML=h;modal.querySelector("#mm-prev").onclick=()=>{calendarDate=new Date(y,m-1,1);render()};modal.querySelector("#mm-next").onclick=()=>{calendarDate=new Date(y,m+1,1);render()}}
function growth(c){const monthMap={};entries.forEach(x=>{const d=dateOf(x),k=`${d.getFullYear()}-${d.getMonth()}`;if(!monthMap[k])monthMap[k]={date:new Date(d.getFullYear(),d.getMonth(),1),count:0,moods:[]};monthMap[k].count++;if(x.mood)monthMap[k].moods.push(x.mood)});const months=Object.values(monthMap).sort((a,b)=>a.date-b.date).slice(-6);const total=entries.length;const moodCounts=entries.filter(x=>x.mood).reduce((a,x)=>(a[x.mood]=(a[x.mood]||0)+1,a),{});const common=Object.entries(moodCounts).sort((a,b)=>b[1]-a[1])[0]?.[0];const longest=entries.length?calculateStreak():0;c.innerHTML=`<div class="mm-phase-card"><h3 style="margin-top:0">🌱 Your Growth Timeline</h3><p style="color:#887b9d;font-size:13px">A simple view of how your journaling journey is growing over time.</p><div class="mm-growth-grid"><div class="mm-growth-stat"><strong>${total}</strong><span>Total journal entries</span></div><div class="mm-growth-stat"><strong>${common?moodMap[common]?.emoji:'—'}</strong><span>Most common mood</span></div><div class="mm-growth-stat"><strong>${longest} day${longest===1?'':'s'}</strong><span>Best journaling streak</span></div></div>${months.length?`<div class="mm-growth-timeline">${months.map(x=>{const max=Math.max(...months.map(y=>y.count),1);const cm=x.moods.length?x.moods.reduce((a,m)=>(a[m]=(a[m]||0)+1,a),{}):{};const cmood=Object.entries(cm).sort((a,b)=>b[1]-a[1])[0]?.[0];return `<div class="mm-growth-bar-wrap"><span class="mm-growth-mood">${cmood?moodMap[cmood]?.emoji:''}</span><div class="mm-growth-bar" style="height:${Math.max(8,(x.count/max)*155)}px"></div><span class="mm-growth-label">${x.date.toLocaleString('en-IN',{month:'short'})}</span></div>`}).join('')}</div><div class="mm-growth-note">${total<3?'Keep writing — your timeline will become more meaningful as you add entries.':`You've built ${total} memories so far. Keep noticing how your thoughts and moods change from month to month. 💜`}</div>`:'<div class="mm-growth-note">Write a few journal entries to start building your growth timeline.</div>'}</div>`}
function calculateStreak(){const days=new Set(entries.map(x=>dateKey(dateOf(x))));let best=0,current=0;const sorted=[...days].sort();for(let i=0;i<sorted.length;i++){if(i===0||Math.round((new Date(sorted[i])-new Date(sorted[i-1]))/86400000)===1)current++;else current=1;best=Math.max(best,current)}return best}
onAuthStateChanged(auth,async u=>{user=u;if(u)await loadEntries();ensureButton()});
const obs=new MutationObserver(()=>{ensureButton();if(modal&&user&&!document.body.contains(modal))modal=null});obs.observe(document.body,{childList:true,subtree:true});
`;
