import { collection, getDocs, query, where } from "firebase/firestore";
import { auth, db } from "./firebase";

const API = "https://mindmate-kuqp.onrender.com";
const MOODS = { great: "😄", good: "😌", okay: "😐", low: "😔", rough: "😣" };
let cachedEntries = [];
let calendarDate = new Date();

const style = document.createElement("style");
style.textContent = `
.mm-p1-overlay{position:fixed;inset:0;z-index:13000;background:rgba(30,20,50,.32);backdrop-filter:blur(5px);display:grid;place-items:center;padding:20px}.mm-p1-card{width:min(780px,100%);max-height:88vh;overflow:auto;background:#fffafc;border:1px solid #ddd1f3;border-radius:24px;padding:26px;box-shadow:0 24px 70px rgba(45,30,85,.28);font-family:Arial,sans-serif;color:#403361}.mm-p1-head{display:flex;justify-content:space-between;gap:18px;margin-bottom:20px}.mm-p1-head h2{margin:0 0 5px;color:#38266f;font-size:26px}.mm-p1-head p{margin:0;color:#857999;font-size:13px}.mm-p1-close{width:36px;height:36px;border:1px solid #ddd2ef;border-radius:10px;background:#f6f1ff;color:#66557f;font-size:22px}.mm-p1-input{width:100%;box-sizing:border-box;padding:14px;border:1px solid #d9cfee;border-radius:12px;background:#fff;outline:0;color:#443663}.mm-p1-btn{border:0;border-radius:12px;padding:12px 17px;background:#7653d7;color:#fff;font-weight:700;cursor:pointer}.mm-p1-btn.alt{background:#eee7ff;color:#57417f}.mm-p1-answer{margin-top:16px;padding:17px;border-radius:16px;background:#f8f4ff;border:1px solid #e3daf2;line-height:1.65;white-space:pre-wrap;color:#5b4d70}.mm-p1-calendar-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.mm-p1-calendar-head button{width:36px;height:36px;border:1px solid #ddd2ef;border-radius:10px;background:#f4efff;color:#5c4781;font-size:20px}.mm-p1-calendar-head strong{font-size:18px}.mm-p1-week,.mm-p1-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:7px}.mm-p1-week div{text-align:center;font-size:10px;color:#978aa5;font-weight:700}.mm-p1-grid{margin-top:7px}.mm-p1-day{min-height:76px;border:1px solid #e1d7ef;border-radius:12px;padding:7px;background:#fff;text-align:left}.mm-p1-day.today{border-color:#8b6bd0;box-shadow:0 0 0 2px #eee7ff}.mm-p1-day-num{font-size:11px;color:#8e829c}.mm-p1-day-mood{font-size:25px;margin-top:7px}.mm-p1-day-count{font-size:9px;color:#978ba5}.mm-p1-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin-bottom:20px}.mm-p1-stat{padding:17px;border:1px solid #e1d7ef;border-radius:16px;background:#faf8ff}.mm-p1-stat strong{display:block;font-size:25px;color:#6045a0}.mm-p1-stat span{font-size:11px;color:#877a98}.mm-p1-month{display:grid;grid-template-columns:90px 1fr 35px;align-items:center;gap:9px;margin:10px 0;font-size:12px}.mm-p1-bar{height:9px;border-radius:99px;background:#eee7f8;overflow:hidden}.mm-p1-bar i{display:block;height:100%;border-radius:99px;background:#8b6bd0}.mm-p1-suggestion{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin-top:15px}.mm-p1-suggestion button{text-align:left;min-height:70px;border:1px solid #e0d5f0;border-radius:14px;background:#faf8ff;padding:13px;color:#59467d;font-weight:600;cursor:pointer}.mm-p1-suggestion button:hover{background:#f0e9ff}.mm-p1-note{margin-top:15px;color:#897d9a;font-size:11px;line-height:1.5}
.dark-mode .mm-p1-card{background:#2d273d;border-color:#514667;color:#eee8ff}.dark-mode .mm-p1-head h2{color:#f1eaff}.dark-mode .mm-p1-head p,.dark-mode .mm-p1-note{color:#b9aecb}.dark-mode .mm-p1-input{background:#252031;color:#eee8ff;border-color:#554a69}.dark-mode .mm-p1-answer,.dark-mode .mm-p1-stat,.dark-mode .mm-p1-day,.dark-mode .mm-p1-suggestion button{background:#352e47;border-color:#55496b;color:#eee8ff}.dark-mode .mm-p1-calendar-head button,.dark-mode .mm-p1-btn.alt{background:#40365a;color:#eee8ff;border-color:#5b4e72}.dark-mode .mm-p1-day-num,.dark-mode .mm-p1-day-count,.dark-mode .mm-p1-week div{color:#b7acc9}
@media(max-width:650px){.mm-p1-card{padding:19px}.mm-p1-stats{grid-template-columns:1fr}.mm-p1-grid,.mm-p1-week{gap:4px}.mm-p1-day{min-height:62px;padding:5px}.mm-p1-suggestion{grid-template-columns:1fr}}
`;
document.head.appendChild(style);

const esc = (v) => String(v ?? "").replace(/[&<>\"]/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;"}[c]));
const dateOf = (v) => v?.toDate ? v.toDate() : new Date(v || 0);
const dateText = (v) => dateOf(v).toLocaleDateString("en-IN", { day:"numeric", month:"short", year:"numeric" });
async function loadEntries(){ if(!auth.currentUser){cachedEntries=[];return;} const q=query(collection(db,"journalEntries"),where("userId","==",auth.currentUser.uid)); const snap=await getDocs(q); cachedEntries=snap.docs.map(d=>({id:d.id,...d.data()})).sort((a,b)=>dateOf(b.createdAt)-dateOf(a.createdAt)); }
function close(){document.querySelector(".mm-p1-overlay")?.remove()}
function modal(title,sub,body){close();const o=document.createElement("div");o.className="mm-p1-overlay";o.innerHTML=`<section class="mm-p1-card"><div class="mm-p1-head"><div><h2>${title}</h2><p>${sub}</p></div><button class="mm-p1-close">×</button></div>${body}</section>`;o.querySelector(".mm-p1-close").onclick=close;o.onclick=e=>{if(e.target===o)close()};document.body.appendChild(o);return o.querySelector(".mm-p1-card")}
function ask(){const c=modal("🧠 Ask MindMate","Your journal, now conversational. Ask about your own entries and patterns.",`<input class="mm-p1-input" id="p1q" placeholder="What has been making me happiest lately?"><div style="margin-top:12px"><button class="mm-p1-btn" id="p1ask">Ask MindMate</button></div><div id="p1a"></div><div class="mm-p1-suggestion"><button>What topics keep coming up in my journal?</button><button>What seems to improve my mood?</button><button>What am I proud of recently?</button><button>What patterns should I pay attention to?</button></div>`);const q=c.querySelector("#p1q"),a=c.querySelector("#p1a");c.querySelectorAll(".mm-p1-suggestion button").forEach(b=>b.onclick=()=>{q.value=b.textContent;q.focus()});c.querySelector("#p1ask").onclick=async()=>{if(!q.value.trim())return;a.innerHTML=`<div class="mm-p1-answer">🤖 MindMate is thinking...</div>`;try{const r=await fetch(`${API}/ask`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:q.value.trim(),entries:cachedEntries.slice(0,25).map(x=>({date:dateText(x.createdAt),mood:x.mood,text:x.text}))})});const d=await r.json();if(!r.ok)throw Error();a.innerHTML=`<div class="mm-p1-answer">${esc(d.answer)}</div>`}catch{a.innerHTML=`<div class="mm-p1-answer">MindMate could not answer right now. Please try again later.</div>`}}}
function calendar(){const c=modal("📊 Mood Calendar","A month-by-month view of the moods you saved with your journal entries.",`<div class="mm-p1-calendar-head"><button id="p1prev">‹</button><strong id="p1month"></strong><button id="p1next">›</button></div><div class="mm-p1-week"><div>Sun</div><div>Mon</div><div>Tue</div><div>Wed</div><div>Thu</div><div>Fri</div><div>Sat</div></div><div class="mm-p1-grid" id="p1cal"></div>`);const draw=()=>{const y=calendarDate.getFullYear(),m=calendarDate.getMonth(),days=new Date(y,m+1,0).getDate(),start=new Date(y,m,1).getDay();c.querySelector("#p1month").textContent=calendarDate.toLocaleString("en-IN",{month:"long",year:"numeric"});let html="";for(let i=0;i<start;i++)html+="<div></div>";for(let day=1;day<=days;day++){const list=cachedEntries.filter(x=>{const d=dateOf(x.createdAt);return d.getFullYear()===y&&d.getMonth()===m&&d.getDate()===day});const mood=list.find(x=>x.mood)?.mood;const today=new Date();const isToday=today.getFullYear()===y&&today.getMonth()===m&&today.getDate()===day;html+=`<div class="mm-p1-day ${isToday?"today":""}"><div class="mm-p1-day-num">${day}</div><div class="mm-p1-day-mood">${MOODS[mood]||"·"}</div><div class="mm-p1-day-count">${list.length?`${list.length} ${list.length===1?"entry":"entries"}`:""}</div></div>`}c.querySelector("#p1cal").innerHTML=html};c.querySelector("#p1prev").onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()-1,1);draw()};c.querySelector("#p1next").onclick=()=>{calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+1,1);draw()};draw()}
function growth(){const days=[...new Set(cachedEntries.map(x=>dateOf(x.createdAt).toDateString()))];let streak=0,d=new Date();while(days.includes(d.toDateString())){streak++;d.setDate(d.getDate()-1)}const moods=cachedEntries.reduce((a,x)=>{if(x.mood)a[x.mood]=(a[x.mood]||0)+1;return a},{}),common=Object.entries(moods).sort((a,b)=>b[1]-a[1])[0];const months={};cachedEntries.forEach(x=>{const d=dateOf(x.createdAt),k=`${d.getFullYear()}-${d.getMonth()}`;months[k]=(months[k]||0)+1});const recent=Object.entries(months).sort().slice(-6),max=Math.max(1,...recent.map(x=>x[1]));const c=modal("🌱 Your Growth","See your consistency and how your journaling has changed over time.",`<div class="mm-p1-stats"><div class="mm-p1-stat"><strong>${cachedEntries.length}</strong><span>Total entries</span></div><div class="mm-p1-stat"><strong>${streak}</strong><span>Current streak</span></div><div class="mm-p1-stat"><strong>${common?MOODS[common[0]]:"—"}</strong><span>Most recorded mood</span></div></div><h3>Journaling over time</h3>${recent.length?recent.map(([k,n])=>{const [y,m]=k.split("-");const label=new Date(+y,+m,1).toLocaleString("en-IN",{month:"short"});return `<div class="mm-p1-month"><span>${label} ${y}</span><div class="mm-p1-bar"><i style="width:${Math.round(n/max*100)}%"></i></div><b>${n}</b></div>`}).join(""):"<div class='mm-p1-answer'>Write a few entries and your growth story will start here.</div>"}<div id="p1growthai" style="margin-top:18px"></div>`);const ai=c.querySelector("#p1growthai");const b=document.createElement("button");b.className="mm-p1-btn";b.textContent="✨ Generate my growth reflection";ai.appendChild(b);b.onclick=async()=>{b.disabled=true;b.textContent="🤖 Reflecting...";try{const r=await fetch(`${API}/ask`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:"Give me a warm, concise reflection on my journaling growth. Mention recurring themes, mood patterns, consistency, and one encouraging observation. Do not diagnose me or invent anything.",entries:cachedEntries.slice(0,25).map(x=>({date:dateText(x.createdAt),mood:x.mood,text:x.text}))})});const d=await r.json();if(!r.ok)throw Error();ai.innerHTML=`<div class="mm-p1-answer">${esc(d.answer)}</div>`}catch{b.disabled=false;b.textContent="✨ Try again"}}}
function nav(label,icon,fn){const s=document.querySelector(".sidebar");if(!s||s.querySelector(`[data-p1="${label}"]`))return;const b=document.createElement("button");b.className="side-item mm-p1-nav";b.dataset.p1=label;b.innerHTML=`<span>${icon}</span> ${label}`;b.onclick=async e=>{e.stopPropagation();try{await loadEntries()}catch{}fn()};s.insertBefore(b,s.querySelector(".sidebar-bottom")||null)}
function wire(){if(!document.querySelector(".sidebar"))return;nav("Ask MindMate","🧠",ask);nav("Mood Calendar","📊",calendar);nav("Your Growth","🌱",growth)}
function start(){wire();new MutationObserver(()=>requestAnimationFrame(wire)).observe(document.body,{childList:true,subtree:true});setInterval(wire,1000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
