import { auth } from "./firebase";

const STYLE_ID = "mindmate-water-style";
const todayKey = () => new Date().toISOString().slice(0, 10);
const storageKey = () => `mindmate-water-${auth.currentUser?.uid || "guest"}-${todayKey()}`;
const getWater = () => Number(localStorage.getItem(storageKey()) || 0);
const setWater = (value) => localStorage.setItem(storageKey(), String(Math.max(0, Math.min(4, value))));

const css = `.water-card{height:100%;min-height:150px;background:rgba(255,255,255,.76);border:1px solid #ddd2f1;border-radius:20px;padding:20px;box-shadow:0 10px 30px rgba(72,49,130,.08);box-sizing:border-box}.water-card h3{margin:0 0 4px;color:#382a63;font-size:18px}.water-sub{margin:0 0 12px;color:#827697;font-size:12px}.water-total{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:11px}.water-number{font-size:25px;font-weight:800;color:#6045a0}.water-track{height:8px;background:#eee8f8;border-radius:99px;overflow:hidden;flex:1}.water-fill{height:100%;width:0;background:linear-gradient(90deg,#a98ce6,#7655d3);border-radius:99px;transition:.25s}.water-milestones{display:grid;grid-template-columns:repeat(4,1fr);gap:5px}.water-milestone{text-align:center;padding:6px 2px;border:1px solid #e4dcf1;border-radius:11px;background:#fbf9ff;opacity:.55;transition:.2s}.water-milestone.active{opacity:1;background:#f1eaff;border-color:#bca8e8;transform:translateY(-1px)}.water-icon{font-size:23px;line-height:1}.water-liters{display:block;margin-top:3px;font-size:9px;color:#77698c;font-weight:700}.water-actions{display:flex;gap:7px;margin-top:9px}.water-actions button{flex:1;border:0;border-radius:10px;padding:7px;background:#eee7ff;color:#59417f;font-weight:700;cursor:pointer}.water-actions button:last-child{background:#7655d3;color:#fff}.water-note{margin:8px 0 0;color:#9a8da9;font-size:9px}.dark-mode .water-card{background:rgba(42,36,60,.86);border-color:#4b4262}.dark-mode .water-card h3{color:#eee7ff}.dark-mode .water-sub,.dark-mode .water-note{color:#b9aecb}.dark-mode .water-milestone{background:#302943;border-color:#514668}.dark-mode .water-milestone.active{background:#40345b;border-color:#8f76c9}.dark-mode .water-liters{color:#c2b7d1}.dark-mode .water-track{background:#4b4260}`;
function install(){if(document.getElementById(STYLE_ID))return;const s=document.createElement("style");s.id=STYLE_ID;s.textContent=css;document.head.appendChild(s)}
function renderCard(target){const card=document.createElement("section");card.className="water-card";card.innerHTML=`<h3>💧 Hydration Check</h3><p class="water-sub">A tiny reminder to keep your water nearby.</p><div class="water-total"><span class="water-number">0 L</span><div class="water-track"><div class="water-fill"></div></div></div><div class="water-milestones"><div class="water-milestone" data-l="1"><div class="water-icon">🥛</div><span class="water-liters">1L · half glass</span></div><div class="water-milestone" data-l="2"><div class="water-icon">🥛</div><span class="water-liters">2L · full glass</span></div><div class="water-milestone" data-l="3"><div class="water-icon">🫗</div><span class="water-liters">3L · jug</span></div><div class="water-milestone" data-l="4"><div class="water-icon">🫙</div><span class="water-liters">4L · jar</span></div></div><div class="water-actions"><button data-water="minus">− 0.5L</button><button data-water="plus">+ 0.5L</button></div><p class="water-note">Track what you normally drink; the 4L display is a limit, not a recommendation.</p>`;target.replaceWith(card);const update=()=>{const value=getWater();card.querySelector(".water-number").textContent=`${value.toFixed(1).replace(".0","")} L`;card.querySelector(".water-fill").style.width=`${value/4*100}%`;card.querySelectorAll(".water-milestone").forEach(x=>x.classList.toggle("active",value>=Number(x.dataset.l)))};card.querySelector('[data-water="plus"]').onclick=()=>{setWater(getWater()+.5);update()};card.querySelector('[data-water="minus"]').onclick=()=>{setWater(getWater()-.5);update()};update()}
function wire(){install();document.querySelectorAll(".insights-card").forEach(x=>renderCard(x))}
let started=false;function start(){if(started)return;started=true;wire();new MutationObserver(()=>requestAnimationFrame(wire)).observe(document.body,{childList:true,subtree:true});setInterval(wire,1000)}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
